{% set name = "GeographicLib" %}
# follow python version rules, see https://peps.python.org/pep-0440/
{% set version = "2.1.2" %}
{% set fullversion = "2.1.2" %}

package:
  name: {{ name|lower }}-cpp
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/geographiclib/distrib-C++/GeographicLib-{{ fullversion }}.tar.gz
  sha256: b062b472dae3d371b3005f4ea2fc59af687b8ea76eb23df732ec11c500fba959

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('geographiclib-cpp', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - GeoConvert --version
    - GeodSolve -i --input-string "1 2 3 4"

about:
  home: https://geographiclib.sourceforge.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A small C++ library for geographic conversions
  description: |
    GeographicLib is a small C++ library for: geodesic and rhumb line
    calculations; conversions between geographic, UTM, UPS, MGRS,
    geocentric, and local cartesian coordinates; gravity (e.g.,
    EGM2008) and geomagnetic field (e.g., WMM2020) calculations.
  doc_url: https://geographiclib.sourceforge.io/C++/{{ fullversion }}

extra:
  recipe-maintainers:
    - cffk
