{% set name = "GeographicLib" %}
{% set version = "1.52" %}

package:
  name: {{ name|lower }}-cpp
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/geographiclib/distrib/GeographicLib-{{ version }}.tar.gz
  sha256: 5d4145cd16ebf51a2ff97c9244330a340787d131165cfd150e4b2840c0e8ac2b
  patches:
    - cxx-components-only.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('geographiclib-cpp', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - GeoConvert --version
    - GeodSolve -i --input-string "20.001 0 20.001 0" -f -p 12

about:
  home: https://geographiclib.sourceforge.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A small C++ library for geographic conversions
  description: |
    GeographicLib is a small set of C++ classes for performing
    conversions between geographic, UTM, UPS, MGRS, geocentric, and
    local cartesian coordinates, for gravity (e.g., EGM2008), geoid
    height, and geomagnetic field (e.g., WMM2020) calculations, and
    for solving geodesic problems.
  doc_url: https://geographiclib.sourceforge.io/{{ version }}

extra:
  recipe-maintainers:
    - cffk
