{% set name = "GeographicLib" %}
# follow python version rules, see https://peps.python.org/pep-0440/
{% set version = "2.0" %}
{% set fullversion = "2.0" %}

package:
  name: {{ name|lower }}-cpp
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/geographiclib/distrib-C++/GeographicLib-{{ fullversion }}.tar.gz
  sha256: 906b862aa9e988534fd5b8d9f3bae07437e0079a4236e19942ab61fe8c83960b

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('geographiclib-cpp', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - GeoConvert --version
    - GeodSolve -i --input-string "1 2 3 4"

about:
  home: https://geographiclib.sourceforge.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A small C++ library for geographic conversions
  description: |
    GeographicLib is a small set of C++ classes for performing
    conversions between geographic, UTM, UPS, MGRS, geocentric, and
    local cartesian coordinates, for gravity (e.g., EGM2008), geoid
    height, and geomagnetic field (e.g., WMM2020) calculations, and
    for solving geodesic problems.
  doc_url: https://geographiclib.sourceforge.io/C++/{{ fullversion }}

extra:
  recipe-maintainers:
    - cffk
